### ISSUE TITLE
Auto size text does not auto-size text in the Flutter stable  v1.2.1

### ISSUE THREAD

**Issue by jeffersonatsafe** [leisim/auto_size_text#10]
I was on Flutter Beta 1.0 for the longest time in one of my machines. 
Today I upgraded to Flutter Stable v1.2.1, and seems that this plugin has lost its functionality. 
Text is not being auto-sized properly, even with `maxLines` and `minFontSize` specified. 

plugin version: 1.1.1

code snippet: 
```
        Card(
          margin: EdgeInsets.only(top: 12.0),
          elevation: 4.0,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: AutoSizeText(
              "this is a very very very very very very very very very very long string",
              maxLines: 1,
              minFontSize: 2.0,
            ),
          ),
        ),
```

flutter doctor output: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648],
    locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected device (1 available)
```

**Comment by leisim** [comment]
Please try wrapping your `Card` with a `SizedBox`.

**Comment by jeffersonatsafe** [comment]
I've tried wrapping with a `SizedBox`, and then varying its width. 

The text does resize with different width values, to a certain extent, but it still doesn't try to show the entire length of the string. It appears as if it's applying overflow truncation before resizing. 

here's my modified code (with SizedBox) and a screenshot of what I'm seeing on my screen. I also varied the text scaling factor on the device to test this. 

As seen in the screenshot, notice that the text is faded on the bottom. Does this mean that overflow has been applied to the text? 

```
  @override
  Widget build(BuildContext context) {
    var stackContents = [
        SizedBox(
          width: 240,
          child: Card(
            margin: EdgeInsets.only(top: 12.0),
            elevation: 4.0,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: AutoSizeText(
                "hello kind sir, thank you, good bye",
//                "${_selectedLocation.latitude}, ${_selectedLocation.longitude}",
                maxLines: 1,
                maxFontSize: 24.0,
                overflow: TextOverflow.fade,
                minFontSize: 2.0,
              ),
            ),
          ),
        ),
    ];
    return Scaffold(
      appBar: AppBar(
        title: Text("Select Location"),
      ),
      body: Stack(
        children: stackContents,
      ),
    );
```

screenshot: 
<a href="https://ibb.co/yXjNjSk"><img src="https://i.ibb.co/wRmdmsQ/Screenshot-20190327-155617.jpg" alt="Screenshot-20190327-155617" border="0"></a><br />

**Comment by leisim** [comment]
Thanks for the information. I'll investigate this problem.

**Comment by leisim** [comment]
I sadly cannot reproduce your problem. I tried it with multiple flutter versions including `v1.2.1`  and `v1.4.2-pre.3`. The text always resizes and fits the card.
I used this code from your sample:
```dart
class App extends StatefulWidget {
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {

  @override
  Widget build(BuildContext context) {
    var stackContents = [
      SizedBox(
        width: 180,
        child: Card(
          margin: EdgeInsets.only(top: 12.0),
          elevation: 4.0,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: AutoSizeText(
              "hello kind sir, thank you, good bye",
              maxLines: 1,
              maxFontSize: 24.0,
              overflow: TextOverflow.fade,
              minFontSize: 2.0,
            ),
          ),
        ),
      ),
    ];

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Select Location"),
        ),
        body: Stack(
          children: stackContents,
        ),
      ),
    );
  }
}
```

Maybe try it with an empty project. If you still have problem it would be nice if you could share a sample project so I can reproduce the problem.

**Comment by jeffersonatsafe** [comment]
thanks for looking into this!
Sadly, I'm still experiencing this problem, even in a relatively barebones project. 
I've applied AutoSizeText to Flutter's getting_started project here: 
https://github.com/jeffersonatsafe/flutterAutoSizeTextIssue

this is a screenshot of the project on a Galaxy S9, with font size (on the device) 4th from the left. 
The three lines share the same `minFontSize`, only differing in `SizedBox` width. 
Notice that the second line, although has more width than the first line, truncates more words. 
<a href="https://ibb.co/zFKg550"><img src="https://i.ibb.co/C6xyttT/Screenshot-20190328-104719.jpg" alt="Screenshot-20190328-104719" border="0"></a><br />

**Comment by jeffersonatsafe** [comment]
update: 
I think I might be wrong in assuming that the Flutter update caused this. 
I rolled back to 1.0.0, and the issue is still there. 

I think increasing the font size in the device itself is causing this problem, and I can't seem to recall if I tested with device font sizes in older flutter builds. This might not be a regression issue after all. 

On Android devices, changing the device's display size (not font size) seem to work well. It's when I was changing the device's font size that this issue start to happen. 

The issue also occurs on iOS device when using Accesibility > Larger Text settings.

**Comment by jeffersonatsafe** [comment]
ok I've done more investigation, and I see that flutter update did not cause this. 
Something caused this between `auto_size_text v1.0.0` and `auto_size_text_v1.1.1`
I rolled back to 1.0.0 and the problem went away.

**Comment by leisim** [comment]
Sorry for the late response, I'm very busy currently. It may take a few more days to fix this...

**Comment by leisim** [comment]
I found the problem and fixed it. Thanks for your help. The new version (1.1.2) should be available soon. Please reopen the issue if it still doesn't work for you.

**Comment by mahmoudsalah37** [comment]
it is not work with me inside Expanded

**Comment by giandifra** [comment]
It's pretty strange, I pass a variable to AutoSizeText widget and it not work, if i pass it a string it work! 

Don't work
```
...
Container(
                      color: Colors.red,
                      height: 40,
                      child: AutoSizeText(
                        link,
                        maxLines: 1,
                        textAlign: TextAlign.center,
                        style: TextStyle(
                            fontSize: 30, fontWeight: FontWeight.bold),
                      ),
                    ),
...
```

Work:
```
...
Container(
                      color: Colors.red,
                      height: 40,
                      child: AutoSizeText(
                        'https://example.com/example',
                        maxLines: 1,
                        textAlign: TextAlign.center,
                        style: TextStyle(
                            fontSize: 30, fontWeight: FontWeight.bold),
                      ),
                    ),
...
```

PS: The Container is into a Column

**Comment by DenisKen** [comment]
My auto_size_text doesn't work too.
![image](https://user-images.githubusercontent.com/15076521/94749762-f8bce100-035a-11eb-8f00-9d3dc9e82782.png)

```
     SizedBox(
            height: SizeConfig.blockSizeVertical * 20,
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  AutoSizeText(
                    "buy-premium-verion_subtitle_1".tr(),
                    style: ThemeText.roboto_medium_18_white,
                    minFontSize: 0,
                  ),
                  AutoSizeText(
                    "buy-premium-verion_subtitle_1_1".tr(),
                    style: ThemeText.roboto_medium_26_brightgreen,
                    minFontSize: 0,
                  ),
                  AutoSizeText(
                    "buy-premium-verion_subtitle_2".tr(),
                    style: ThemeText.roboto_medium_18_white,
                    minFontSize: 0,
                  ),
                  AutoSizeText(
                    "buy-premium-verion_subtitle_2_1".tr(),
                    style: ThemeText.roboto_medium_26_brightgreen,
                    minFontSize: 0,
                  )
                ]),
            )
```
Am I doing something wrong? 
This SizedBox is inside of a Column and a Container with Padding

**Comment by EliaTolin** [comment]
> It's pretty strange, I pass a variable to AutoSizeText widget and it not work, if i pass it a string it work!
> 
> Don't work
> 
> ```
> ...
> Container(
>                       color: Colors.red,
>                       height: 40,
>                       child: AutoSizeText(
>                         link,
>                         maxLines: 1,
>                         textAlign: TextAlign.center,
>                         style: TextStyle(
>                             fontSize: 30, fontWeight: FontWeight.bold),
>                       ),
>                     ),
> ...
> ```
> 
> Work:
> 
> ```
> ...
> Container(
>                       color: Colors.red,
>                       height: 40,
>                       child: AutoSizeText(
>                         'https://example.com/example',
>                         maxLines: 1,
>                         textAlign: TextAlign.center,
>                         style: TextStyle(
>                             fontSize: 30, fontWeight: FontWeight.bold),
>                       ),
>                     ),
> ...
> ```
> 
> PS: The Container is into a Column
> 
> Flutter Channel stable, v1.12.13+hotfix.8

You have fix that? 
I have the same problem.
