### ISSUE TITLE
Performance penalty?

### ISSUE THREAD

**Issue by fzyzcjy** [leisim/auto_size_text#108]
Hi thanks for the lib! I wonder whether this will introduce some performance penalty? Because theoretically speaking, the library uses a binary search to see what text size fits the layout. Thus, it invokes text layouting algorithm for a few more times.

**Comment by bw-flagship** [comment]
Maybe this does not answer your question completely, but the readme says:

> AutoSizeText is really fast. In fact, you can replace all your Text widgets with AutoSizeText.
> Nevertheless you should not use an unreasonable high fontSize in your TextStyle. E.g. don't set the fontSize to 1000 if you know, that the text will never be larger than 30.
> 
> If your font size has a very large range, consider increasing stepGranularity.
