### ISSUE TITLE
Android bug what is it?

### ISSUE THREAD

**Issue by 1AlexFix1** [leisim/auto_size_text#11]
```
Container(
                        height: 50,
                        width: 40,
                        alignment: Alignment.center,
                        child: AutoSizeText(
                          '999',
                          style: TextStyle(fontSize: 100),
                          textAlign: TextAlign.center,
                          maxLines: 1,
                        ),
                      ),
```
This code works fine in any IOS device, but on Android, the last letter goes to the next line, if you slightly increase the height you will see why this happens?
But FittedBox help this

**Comment by leisim** [comment]
I'm looking into this...

**Comment by leisim** [comment]
Your sample works fine for me. Even if I change the width or height of the container...
Could you test it again and maybe create a small test project?

**Comment by 1AlexFix1** [comment]
> Your sample works fine for me. Even if I change the width or height of the container...
> Could you test it again and maybe create a small test project?


There is a problem in that it is reproduced on my real device honor 8, while on the emulator everything worked fine. I'll take a few more phones and test them on the answer as soon as I do it.

**Comment by 1AlexFix1** [comment]
I launched on several real devices and everything is OK there, this is a very strange bug, I go into the phone settings, I didn’t change anything with the text, everything is default, how do you think it could be? my phone honor 8 model FRD-L09

**Comment by leisim** [comment]
Are you using auto_size_text v1.1.2?
If not please update to the latest version.
Also try setting your `minFontSize` to `0`.

**Comment by ajkerfaisal** [comment]
> Are you using auto_size_text v1.1.2?
> If not please update to the latest version.
> Also try setting your `minFontSize` to `0`.

by setting minFontSize it resolved for me

**Comment by leisim** [comment]
The problem was that one of your phones seems to have a slightly larger font size and your `AutoSizeText` hit the `minFontSize` and could not resize further...

**Comment by 1AlexFix1** [comment]
done! thank you
