### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by mobiluse** [leisim/auto_size_text#137]
Hello. I came by this package and it's not maintaining now. I would be thankful if you transfer ownership of this to me. I've more than 2 years of experience in flutter.

**Comment by mobiluse** [comment]
@simc

**Comment by vanyasem** [comment]
@mobiluse what stops you from forking the repo first, making the proposed changes, and coming back with some real results in a PR before begging for repo ownership?

**Comment by mobiluse** [comment]
I didn't begged for ownership @vanyasem ! He is not updating it that's why I proposed him to give up his ownership or share ownership with me.

**Comment by vanyasem** [comment]
@mobiluse hey complete stranger! I noticed you haven't visited your garage for a while, mind giving me the keys for it? I promise I will keep it clean and tidy!

**Comment by mobiluse** [comment]
@vanyasem hey. I don't have garage. Please do know what I have.
I asked him for ownership didn't begged for ownership. It's his ownership not yours like you're talking.
Reply to the message where you're asked. Don't get fixed to conversation where you're nothing.

**Comment by mobiluse** [comment]
72 Opened Issues.
9 Opened PRs.
Do you really think he've enough time to fix these for those who're developing enterprise softwares ? 
Are you really a developer ?
@vanyasem
