### ISSUE TITLE
Does not work correctly with large fonts setting

### ISSUE THREAD

**Issue by dalewking** [leisim/auto_size_text#16]
Android devices (and I assume iOS devices as well) have a setting to control font sizing so that if you have trouble seeing you can scale fonts up across the entire device. When this is enabled on a device, it is not taken into account in this library so that this library determines the font size that will fit but then it gets scaled up from there.

You can read about this setting from a flutter perspective in this article in the section on Large Fonts: https://medium.com/flutter-community/a-deep-dive-into-flutters-accessibility-widgets-eb0ef9455bc

**Comment by leisim** [comment]
Are you sure you are using the latest version of `AutoSizeText`? This should already work...

**Comment by dalewking** [comment]
Nope, I was not using the latest

**Comment by leisim** [comment]
Is it fixed?

**Comment by dalewking** [comment]
I didn't bother to test it, but I was using version 1.0.0 and this is a duplicate of another issue that was fixed in 1.1.2 and I reviewed what that fix was and agree that it should be fixed.
