### ISSUE TITLE
Unexpected wrapping with text height style and maxLines > 1

### ISSUE THREAD

**Issue by insin** [leisim/auto_size_text#19]
Thanks for making this widget, I've been a grateful user of it in pretty much every Flutter app I've made so far 👍

I saw a weird text wrapping case in an app I was working on which uses auto_size_text 1.1.2 and thought I'd report it in case this was something the text fitting detection could handle, or if the cause is something users should avoid doing.

I noticed a number of cases where certain single word text was having its last letter wrapped, like so:

![studio64_AECas57Jjb](https://user-images.githubusercontent.com/226692/58482232-55295280-81a1-11e9-87f4-fb113c182412.png)

I was able to make it resize as expected by setting `maxLines` to `1` or by omitting the text `height` styling (the workaround I ended using was only setting maxLines to `2` if the text contains a space).

![7PbxWXPDjo](https://user-images.githubusercontent.com/226692/58482263-683c2280-81a1-11e9-8a42-0f3949bb9230.png)

Other version info:
```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (4 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by leisim** [comment]
Thanks for reporting this.
Could you please test `auto_size_text: 2.0.0-dev` with the new parameter `wrapWords: false`.

This should solve your problem.
