### ISSUE TITLE
wrapWords not working

### ISSUE THREAD

**Issue by kevin-haynie** [leisim/auto_size_text#21]
Even with wrapWords = false, autoSizeText still breaks up a single word - see screenshot.

**Steps to Reproduce**
Set wrapWords = false, maxFontSize = 200, minFontSize = 20, data="BECAUSE I'M LOVIN' IT!"

**Screenshots**
![image](https://user-images.githubusercontent.com/4258624/59046518-2de11e00-8850-11e9-8d2d-434153cc22fc.png)

**Version**
 - Flutter version: [e.g. 1.7.2]
 - auto_size_text version: [2.0.0+2]

**Comment by leisim** [comment]
Thanks, I'll check that...

**Comment by leisim** [comment]
Thank you for reporting this bug! It is fixed in version `2.0.1`.

**Comment by kevin-haynie** [comment]
yup, you fixed it!  thanks so much.  good work.
