### ISSUE TITLE
Start with 1 line and move to 2?

### ISSUE THREAD

**Issue by warriorCoder** [leisim/auto_size_text#23]
**Question**
Is it possible to fit the text to one line at a specified font size and only if the text doesn't fix at a predetermined size is the font increased and the number of lines increased to two?

**Code sample**
AutoSizeText(
            Utility.capitalize(product.name),
            style: Theme.of(context).textTheme.title,
            maxFontSize: 18.0,
            minFontSize: 10.0,
            minLines: 1,
            maxLines: 2,
          ),

**Version**
 - Flutter version: 1.5.4
 - auto_size_text version: 1.2.1

**Comment by leisim** [comment]
This should work:

```dart
AutoSizeText
  myText,
  style: TextStyle(fontSize: 20),
  minFontSize: 14,
  maxLines: 1,
  overflowReplacement: AutoSizeText(
    myText,
    style: TextStyle(fontSize: 24),
    minFontSize: 16
    maxLines: 2,
  ),
)
```

**Comment by warriorCoder** [comment]
Works great!! Thanks so much.
