### ISSUE TITLE
Error calculating dimensions in SimpleDialog

### ISSUE THREAD

**Issue by warriorCoder** [leisim/auto_size_text#24]
**Steps to Reproduce**
- Create a  SimpleDialog being shown in the showDialog call.
- In the title add a row with an expanded widget which holds the AutoSizeText widget

**Code sample**
```dart
Container(
            color: Colors.black12,
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Expanded(
                  child: Padding(
                    padding:
                        const EdgeInsets.only(left: 10, top: 10, bottom: 5),
                    child: AutoSizeText(
                       "Big long huge title here to shrink",
                      style: Theme.of(context).textTheme.title,
                      minFontSize: 14,
                      maxLines: 1,         
                    ),
                  ),
                ),
                IconButton(
                  alignment: Alignment.topRight,
                  icon: Icon(Icons.close),
                  onPressed: () => Navigator.of(context).pop(),
                )
              ],
            ),
          ),
```

**Screenshots**

**Version**
 - Flutter version: [1.5.4]
 - auto_size_text version: [2.0.1]

**Comment by leisim** [comment]
I will look into this as soon as possible...

**Comment by lucadelc** [comment]
Same error here, I cannot use AutoSizeText widget inside dialogs

**Comment by leisim** [comment]
@lucadelc I still haven't had time to look into this :/

**Comment by lucadelc** [comment]
Nothing yet?

**Comment by leisim** [comment]
Sorry, I have exams currently. After that I'll start working on the project again.

If you are in a hurry, maybe you can look into the problem yourself. If you find a solution, please create a pull request :+1:

**Comment by lucadelc** [comment]
No problem mate, take your time, btw I'm a flutter developer but i don't know how to create a plugin at all 😂

**Comment by Ahmadre** [comment]
@lucadelc : you don't need to know how to create a plugin. Fot a quick test: change you local copy of AutoSizeText components and if you succeeded, you can point out your fix here :blush:

**Comment by leisim** [comment]
@warriorCoder Your code works fine for me. But you have to wrap it in a `SizedBox` because the dialog itself does not restrict its children.

**Comment by davidlawson** [comment]
From the AlertDialog docs:

> (However, be aware that since [AlertDialog] tries to size itself using the intrinsic dimensions of its children, widgets such as [ListView], [GridView], and [CustomScrollView], which use lazy viewports, will not work. If this is a problem, consider using [Dialog] directly.)
