### ISSUE TITLE
Can't import this package ver 0.2.2

### ISSUE THREAD

**Issue by lxbees** [leisim/auto_size_text#3]
I'm using flutter 0.11.7 and in the main.dart 
`import 'package:auto_size_text/auto_size_text.dart';` 
i got this error
> [dart] Target of URI doesn't exist: 'package:auto_size_text/auto_size_text.dart'. [uri_does_not_exist]

**Comment by leisim** [comment]
Did you run pub get ?

**Comment by lxbees** [comment]
The problem was from vs code after reopen it , sorry and thanks for answer .
