### ISSUE TITLE
Does not work inside bubble_bottom_bar

### ISSUE THREAD

**Issue by nohli** [leisim/auto_size_text#41]
**Steps to Reproduce**
add package https://pub.dev/packages/bubble_bottom_bar to pubspec.yaml and add BubbleBottomBar as bottomNavigationBar to your Scaffold

**Code sample**
```
      BubbleBottomBarItem(
          ...
          title: AutoSizeText(...
```

**Version**
 - Flutter version: latest stable
 - auto_size_text version: latest from Git (because with the pub.dev version my test failed - https://github.com/leisim/auto_size_text/pull/35)

**Comment by leisim** [comment]
What happens when you use `AutoSizeText` in the `BubbleBottomBarItem`?

**Comment by nohli** [comment]
It seems to do nothing - no error, but 'overflowing' text - like it was normal Text()
