### ISSUE TITLE
OnOverflow callback

### ISSUE THREAD

**Issue by kym6464** [leisim/auto_size_text#56]
**Is your feature request related to a problem? Please describe.**
I want to display a Widget with some text (AutoSizeText) at a *standard size*. If the text overflows, then I want to add a "Read More" button which expands the Widget and shows the full text. 

**Describe the solution you'd like**
A way to branch on the overflow condition. E.g.
```dart
AutoSizeText(
  'A String tool long to display without extreme scaling or overflow.',
  maxLines: 1,
  onOverflow: () => print('Text overflowed'),
)
```

**Describe alternatives you've considered**
`overflowReplacement` parameter is not ideal for this situation, since `AutoSizeText` is almost always a child of some container (e.g. `Card`).

Also, the proposed solutions in [this](https://stackoverflow.com/questions/51114778/how-to-check-if-flutter-text-widget-was-overflowed) StackOverflow question seem messy.

**Version**
 - Flutter version: 1.17.0
 - auto_size_text version: 2.1.0

**PS**
Would love to contribute and make a PR if this seems like a valid use case, and we can agree upon an API ahead of time :)

**Comment by bounty1342** [comment]
Could I ask what's stopping this ? This is something I also encounter.
