### ISSUE TITLE
Publish 3.0.0-nullsafety.0

### ISSUE THREAD

**Issue by cbenhagen** [leisim/auto_size_text#83]
It would be awesome if this package could be [migrated to null safety](https://dart.dev/null-safety/migration-guide).

**Comment by tmnsun** [comment]
Actually it is migrated:
https://github.com/leisim/auto_size_text/pull/76

It needs to be published may be?

**Comment by cbenhagen** [comment]
Oh indeed, even by the Flutter product manager. Sorry I missed that. Yes then it would only need to be published.

**Comment by leisim** [comment]
Done

**Comment by IchordeDionysos** [comment]
@leisim it's now published as a pre-release version for more than 2 months.

Do you feel confident yet to publish this as a stable version?

**Comment by carlosfiori** [comment]
Is the pre-release version stable?

**Comment by nohli** [comment]
@carlosfiori I'm using it in production apps and there has been absolutely no problem.

Maybe @leisim could publish a stable version?

**Comment by BringTheChill** [comment]
@leisim any news?
